# Generated by Django 4.1.7 on 2023-05-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_alter_order_items_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_items',
            name='total',
            field=models.BigIntegerField(),
        ),
    ]
