# Generated by Django 4.1.7 on 2023-05-22 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0004_alter_order_items_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='pay_type',
        ),
        migrations.AddField(
            model_name='order',
            name='pay_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
